# Generated by Django 2.2.7 on 2019-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.CharField(default='https://mysite.ru/', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='ftp_host',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='ftp_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='site',
            name='ftp_user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(default='Новый сайт', max_length=50),
        ),
    ]
