# Generated by Django 2.2.7 on 2019-11-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='region',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Site'),
            preserve_default=False,
        ),
    ]
