# Generated by Django 2.2.7 on 2019-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20191127_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='robots',
            field=models.TextField(default=''),
        ),
    ]
