# Generated by Django 2.2.7 on 2019-11-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_site_robots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый шаблон', max_length=50)),
                ('html', models.TextField(default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Site')),
            ],
            options={
                'verbose_name_plural': 'Шаблоны',
            },
        ),
    ]
