# Generated by Django 2.2.7 on 2019-11-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_placeholder_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placeholder',
        ),
    ]
