# Generated by Django 2.2.7 on 2019-11-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_delete_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая страница', max_length=100)),
                ('alias', models.CharField(default='', max_length=100)),
                ('placeholders', models.TextField(default='')),
                ('metatitle', models.CharField(default='', max_length=80)),
                ('metadescription', models.TextField(default='', max_length=170)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Template')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Site')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
