# Generated by Django 2.2.7 on 2019-12-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20191128_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый чанк', max_length=50)),
                ('html', models.TextField(default='')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Template')),
            ],
            options={
                'verbose_name_plural': 'Чанки',
            },
        ),
    ]
