# Generated by Django 2.2.7 on 2019-12-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='template',
        ),
        migrations.AddField(
            model_name='chunk',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Site'),
            preserve_default=False,
        ),
    ]
