# Generated by Django 2.2.7 on 2019-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20191201_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='phone_tel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
