# Generated by Django 2.2.7 on 2019-12-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_region_phone_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='phone_tel',
        ),
    ]
