# Generated by Django 2.2.7 on 2020-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_region_phone_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='uniqcodes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='uniqwords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(default='mysite.ru', max_length=50),
        ),
    ]
