# Generated by Django 2.2.7 on 2020-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20200118_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='uniqcodes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='uniqwords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
