# Generated by Django 2.2.7 on 2020-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20200118_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='uniqenable',
            field=models.BooleanField(default=False),
        ),
    ]
