# Generated by Django 2.2.7 on 2020-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20200126_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='build_datetime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='build_dir',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='upload',
            field=models.CharField(default='', max_length=255),
        ),
    ]
