# Generated by Django 2.2.7 on 2020-01-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20200126_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='build_datetime',
            new_name='build',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='build_dir',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='upload',
        ),
    ]
