# Generated by Django 2.2.7 on 2020-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20200126_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='main_region',
            field=models.BooleanField(default=False, help_text='Основной регион, размещается на основном домене.'),
        ),
        migrations.AlterField(
            model_name='site',
            name='build',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='upload_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
