# Generated by Django 2.2.7 on 2020-03-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20200128_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='htaccess',
            field=models.TextField(default='', help_text='Содержимое файла .htaccess', verbose_name='.htaccess'),
        ),
        migrations.AlterField(
            model_name='site',
            name='ssl',
            field=models.BooleanField(default=False, help_text='Сайт доступен по протоколу HTTPS', verbose_name='SSL сертификат'),
        ),
    ]
