# Generated by Django 2.2.7 on 2020-03-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20200306_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='htaccess',
        ),
    ]
