# Generated by Django 2.2.7 on 2020-03-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_remove_site_htaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='favicon',
            field=models.CharField(default='assets/images/icons/favicon/favicon.ico', max_length=50, verbose_name='Фавикон'),
        ),
    ]
