# Generated by Django 2.2.7 on 2020-03-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_site_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sitemap_priority',
            field=models.CharField(default='1.0', max_length=5, verbose_name='Приоритет для Sitemap.xml'),
        ),
    ]
