# Generated by Django 2.2.7 on 2020-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_auto_20200413_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='hosting',
            field=models.CharField(default='beget', help_text='beget,regru,timeweb', max_length=50, verbose_name='Хостинг'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(default='Новый сайт', max_length=50, verbose_name='Наименование'),
        ),
    ]
