# Generated by Django 2.2.7 on 2020-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_auto_20200413_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='metadescription',
            field=models.TextField(default='', max_length=300, verbose_name='META-description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='metatitle',
            field=models.CharField(default='', max_length=200, verbose_name='META-title'),
        ),
    ]
