# Generated by Django 3.1 on 2020-11-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_topvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='topvisor',
            name='apikey',
            field=models.CharField(default='', max_length=50, verbose_name='API Ключ'),
        ),
        migrations.AddField(
            model_name='topvisor',
            name='keywords',
            field=models.TextField(default='', verbose_name='Ключевые фразы (без регионов)'),
        ),
        migrations.AddField(
            model_name='topvisor',
            name='userid',
            field=models.CharField(default='', max_length=10, verbose_name='ID пользователя'),
        ),
    ]
